/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPane = new javax.swing.JDesktopPane();
        dadosTempoInternalFrame = new javax.swing.JInternalFrame();
        lblData1 = new javax.swing.JLabel();
        lblTemperatura1 = new javax.swing.JLabel();
        lblUmidade1 = new javax.swing.JLabel();
        lblPressao1 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtUmidade = new javax.swing.JTextField();
        txtPressao = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        dadosMediosInternalFrame = new javax.swing.JInternalFrame();
        lblTemperatura2 = new javax.swing.JLabel();
        lblUmidade2 = new javax.swing.JLabel();
        lblPressão2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registrosInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRegistros = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        ultimaAtualizacaoInternalFrame = new javax.swing.JInternalFrame();
        lblTemperatura3 = new javax.swing.JLabel();
        lblUmidade3 = new javax.swing.JLabel();
        lblPressão3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTempResult3 = new javax.swing.JLabel();
        lblUmidadeResult3 = new javax.swing.JLabel();
        lblPressaoResult3 = new javax.swing.JLabel();
        lblDataResult = new javax.swing.JLabel();
        maximasMinimasInternalFrame = new javax.swing.JInternalFrame();
        lblTemperatura4 = new javax.swing.JLabel();
        lblUmidade4 = new javax.swing.JLabel();
        lblPressao4 = new javax.swing.JLabel();
        configuracaoInternalFrame = new javax.swing.JInternalFrame();
        lblLog = new javax.swing.JLabel();
        cBoxLog = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        lblNumeroRegistros = new javax.swing.JLabel();
        lblRsultNumeroRegistros = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        btnMenuConfigurar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados de clima");
        setResizable(false);

        dadosTempoInternalFrame.setTitle("Dados do tempo");
        dadosTempoInternalFrame.setVisible(true);

        lblData1.setText("Data");

        lblTemperatura1.setText("Temperatura");

        lblUmidade1.setText("Umidade");

        lblPressao1.setText("Pressão");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosTempoInternalFrameLayout = new javax.swing.GroupLayout(dadosTempoInternalFrame.getContentPane());
        dadosTempoInternalFrame.getContentPane().setLayout(dadosTempoInternalFrameLayout);
        dadosTempoInternalFrameLayout.setHorizontalGroup(
            dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosTempoInternalFrameLayout.createSequentialGroup()
                .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dadosTempoInternalFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIncluir))
                    .addGroup(dadosTempoInternalFrameLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData1)
                            .addComponent(lblPressao1)
                            .addComponent(lblUmidade1)
                            .addComponent(lblTemperatura1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData)
                            .addComponent(txtTemperatura)
                            .addComponent(txtUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtPressao))))
                .addGap(34, 34, 34))
        );
        dadosTempoInternalFrameLayout.setVerticalGroup(
            dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosTempoInternalFrameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData1)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura1)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUmidade1)
                    .addComponent(txtUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPressao1)
                    .addComponent(txtPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addGap(14, 14, 14))
        );

        mainPane.add(dadosTempoInternalFrame);
        dadosTempoInternalFrame.setBounds(10, 10, 392, 260);

        dadosMediosInternalFrame.setTitle("Dados médios");
        dadosMediosInternalFrame.setVisible(true);

        lblTemperatura2.setText("Temperatura:");

        lblUmidade2.setText("Umidade:");

        lblPressão2.setText("Pressão:");

        jLabel8.setText("Número de Registros");

        jLabel9.setText("tempResult");

        jLabel10.setText("umidResult");

        jLabel11.setText("pressaoResult");

        jLabel12.setText("nRegisResult");

        javax.swing.GroupLayout dadosMediosInternalFrameLayout = new javax.swing.GroupLayout(dadosMediosInternalFrame.getContentPane());
        dadosMediosInternalFrame.getContentPane().setLayout(dadosMediosInternalFrameLayout);
        dadosMediosInternalFrameLayout.setHorizontalGroup(
            dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMediosInternalFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(lblPressão2)
                    .addComponent(lblUmidade2)
                    .addComponent(lblTemperatura2))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(52, 52, 52))
        );
        dadosMediosInternalFrameLayout.setVerticalGroup(
            dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMediosInternalFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura2)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmidade2)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPressão2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        mainPane.add(dadosMediosInternalFrame);
        dadosMediosInternalFrame.setBounds(410, 10, 286, 260);

        registrosInternalFrame.setTitle("Registros");
        registrosInternalFrame.setVisible(true);

        tbRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Temperatura", "Umidade", "Pressão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbRegistros.setName(""); // NOI18N
        tbRegistros.setShowGrid(true);
        tbRegistros.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tbRegistros);
        tbRegistros.getAccessibleContext().setAccessibleName("");
        tbRegistros.getAccessibleContext().setAccessibleDescription("");

        btnRemover.setText("Remover");

        javax.swing.GroupLayout registrosInternalFrameLayout = new javax.swing.GroupLayout(registrosInternalFrame.getContentPane());
        registrosInternalFrame.getContentPane().setLayout(registrosInternalFrameLayout);
        registrosInternalFrameLayout.setHorizontalGroup(
            registrosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrosInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrosInternalFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemover)))
                .addContainerGap())
        );
        registrosInternalFrameLayout.setVerticalGroup(
            registrosInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrosInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemover)
                .addContainerGap())
        );

        mainPane.add(registrosInternalFrame);
        registrosInternalFrame.setBounds(10, 280, 392, 300);

        ultimaAtualizacaoInternalFrame.setTitle("Última atualização do tempo");
        ultimaAtualizacaoInternalFrame.setVisible(true);
        ultimaAtualizacaoInternalFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        lblTemperatura3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTemperatura3.setText("Temperatura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblTemperatura3, gridBagConstraints);

        lblUmidade3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUmidade3.setText("Umidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 60, 0, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblUmidade3, gridBagConstraints);

        lblPressão3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPressão3.setText("Pressão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 70, 0, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblPressão3, gridBagConstraints);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblData.setText("Data:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 90, 89, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblData, gridBagConstraints);

        lblTempResult3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTempResult3.setText("tempResult");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 14, 0, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblTempResult3, gridBagConstraints);

        lblUmidadeResult3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUmidadeResult3.setText("umidResult");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 0, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblUmidadeResult3, gridBagConstraints);

        lblPressaoResult3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPressaoResult3.setText("pressaoResult");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 0, 28);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblPressaoResult3, gridBagConstraints);

        lblDataResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataResult.setText("dataResult");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 89, 0);
        ultimaAtualizacaoInternalFrame.getContentPane().add(lblDataResult, gridBagConstraints);

        mainPane.add(ultimaAtualizacaoInternalFrame);
        ultimaAtualizacaoInternalFrame.setBounds(410, 280, 300, 300);

        maximasMinimasInternalFrame.setTitle("Máximas e Mínimas");
        maximasMinimasInternalFrame.setVisible(true);

        lblTemperatura4.setText("Temperatura");

        lblUmidade4.setText("Umidade");

        lblPressao4.setText("Pressão");

        javax.swing.GroupLayout maximasMinimasInternalFrameLayout = new javax.swing.GroupLayout(maximasMinimasInternalFrame.getContentPane());
        maximasMinimasInternalFrame.getContentPane().setLayout(maximasMinimasInternalFrameLayout);
        maximasMinimasInternalFrameLayout.setHorizontalGroup(
            maximasMinimasInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maximasMinimasInternalFrameLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblTemperatura4)
                .addGap(138, 138, 138)
                .addComponent(lblUmidade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(lblPressao4)
                .addGap(51, 51, 51))
        );
        maximasMinimasInternalFrameLayout.setVerticalGroup(
            maximasMinimasInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maximasMinimasInternalFrameLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(maximasMinimasInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura4)
                    .addComponent(lblUmidade4)
                    .addComponent(lblPressao4))
                .addGap(25, 25, 25))
        );

        mainPane.add(maximasMinimasInternalFrame);
        maximasMinimasInternalFrame.setBounds(720, 280, 520, 290);

        configuracaoInternalFrame.setTitle("Configuração do Sistema");
        configuracaoInternalFrame.setVisible(false);
        configuracaoInternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLog.setText("Log:");
        configuracaoInternalFrame.getContentPane().add(lblLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        cBoxLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        configuracaoInternalFrame.getContentPane().add(cBoxLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 173, -1));

        btnSalvar.setText("Salvar");
        configuracaoInternalFrame.getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 119, -1, -1));

        mainPane.add(configuracaoInternalFrame);
        configuracaoInternalFrame.setBounds(0, 0, 0, 0);

        lblNumeroRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroRegistros.setText("Número de Registros:");
        mainPane.add(lblNumeroRegistros);
        lblNumeroRegistros.setBounds(1000, 590, 132, 20);

        lblRsultNumeroRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRsultNumeroRegistros.setText("nRegistResult");
        mainPane.add(lblRsultNumeroRegistros);
        lblRsultNumeroRegistros.setBounds(1140, 590, 82, 20);

        menuBar.setDoubleBuffered(true);

        btnMenuConfigurar.setText("Configurar");
        menuBar.add(btnMenuConfigurar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JMenu btnMenuConfigurar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cBoxLog;
    private javax.swing.JInternalFrame configuracaoInternalFrame;
    private javax.swing.JInternalFrame dadosMediosInternalFrame;
    private javax.swing.JInternalFrame dadosTempoInternalFrame;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblDataResult;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNumeroRegistros;
    private javax.swing.JLabel lblPressao1;
    private javax.swing.JLabel lblPressao4;
    private javax.swing.JLabel lblPressaoResult3;
    private javax.swing.JLabel lblPressão2;
    private javax.swing.JLabel lblPressão3;
    private javax.swing.JLabel lblRsultNumeroRegistros;
    private javax.swing.JLabel lblTempResult3;
    private javax.swing.JLabel lblTemperatura1;
    private javax.swing.JLabel lblTemperatura2;
    private javax.swing.JLabel lblTemperatura3;
    private javax.swing.JLabel lblTemperatura4;
    private javax.swing.JLabel lblUmidade1;
    private javax.swing.JLabel lblUmidade2;
    private javax.swing.JLabel lblUmidade3;
    private javax.swing.JLabel lblUmidade4;
    private javax.swing.JLabel lblUmidadeResult3;
    private javax.swing.JDesktopPane mainPane;
    private javax.swing.JInternalFrame maximasMinimasInternalFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JInternalFrame registrosInternalFrame;
    private javax.swing.JTable tbRegistros;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtPressao;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtUmidade;
    private javax.swing.JInternalFrame ultimaAtualizacaoInternalFrame;
    // End of variables declaration//GEN-END:variables
}
